### ISSUE TITLE
[suggestion|lint] wrap code at column 120

### ISSUE THREAD

**Issue by vit-zikmund** [datopian/giftless#143]
Hi folks, namely @athornton. I see you pushed [the spring cleanup](https://github.com/datopian/giftless/issues/126) pretty good! Thanks for that :rocket: 

While currently working in my private fork at https://github.com/datopian/giftless/issues/128, I synced your changes on `main` and carelessly tried `make lint` before a beefy commit :face_with_head_bandage: only to find the code has been wrapped to the 79th column.

While this being entirely a matter of taste, I still want to know if there would be a chance to wrap at the 120th column (PyCharm default). With so many modern "spring" goodies, we could maybe get one more? :innocent: 

Thanks!

**Comment by athornton** [comment]
Well, I chose 79 because it's what my own organization uses and I find short lines and a bigger font much easier on my old eyes, which have a hard time focusing on nearby text (I'm going to guess I have a couple decades on you).

If anyone from Datopian has a preference, feel free to weigh in.  In the meantime @vit-zikmund feel free to set line-length to 120 in [tool.ruff] in pyproject.toml, `make lint` to reformat everything (or `tox -e lint`), develop the way you like, and then set it back and `make lint` again when you're ready to push and PR.  And if Datopian prefers 120, then, well, *I'll* use that workflow in future but with short lines.

**Comment by rufuspollock** [comment]
@athornton at Datopian we generally use 79 character limit. In general here on Giftless we're happy to follow your lead and for you to make choices / recommendations 🙂 - i.e. act as the defacto lead on these matters 🙂

**Comment by vit-zikmund** [comment]
I guess that makes me the single person among all the stakeholders that would want this differently. No problem with that, though. I eventually learned to accept this draconian measure 😄 Long live the 79th column!💪

**Comment by rufuspollock** [comment]
It sounds like a wontfix here as we are sticking with 79. Long live line 79! (may the old ways never die!) 😉

**Comment by rufuspollock** [comment]
WONTFIX
